*Heading
** Job name: Job-3 Model name: Model-1
** Generated by: Abaqus/CAE 2022
*Preprint, echo=NO, model=NO, history=NO, contact=NO
**
** PARTS
**
*Part, name=beam
*Node
      1,           0.,           0.
      2,           1.,           0.
      3,           2.,           0.
      4,           3.,           0.
      5,           4.,           0.
      6,           5.,           0.
      7,           6.,           0.
      8,           7.,           0.
      9,           8.,           0.
     10,           9.,           0.
     11,          10.,           0.
     12,          11.,           0.
     13,          12.,           0.
     14,          13.,           0.
     15,          14.,           0.
     16,          15.,           0.
     17,          16.,           0.
     18,          17.,           0.
     19,          18.,           0.
     20,          19.,           0.
     21,          20.,           0.
     22,          21.,           0.
     23,          22.,           0.
     24,          23.,           0.
     25,          24.,           0.
     26,          25.,           0.
     27,          26.,           0.
     28,          27.,           0.
     29,          28.,           0.
     30,          29.,           0.
     31,          30.,           0.
*Element, type=B21
 1,  1,  2
 2,  2,  3
 3,  3,  4
 4,  4,  5
 5,  5,  6
 6,  6,  7
 7,  7,  8
 8,  8,  9
 9,  9, 10
10, 10, 11
11, 11, 12
12, 12, 13
13, 13, 14
14, 14, 15
15, 15, 16
16, 16, 17
17, 17, 18
18, 18, 19
19, 19, 20
20, 20, 21
21, 21, 22
22, 22, 23
23, 23, 24
24, 24, 25
25, 25, 26
26, 26, 27
27, 27, 28
28, 28, 29
29, 29, 30
30, 30, 31
*Nset, nset=Set-1, generate
  1,  31,   1
*Elset, elset=Set-1, generate
  1,  30,   1
*Nset, nset=Set-Left
 1,
*Nset, nset=Set-right
 31,
*Nset, nset=Set-F
 16,
*Nset, nset=Set-mesh, generate
  2,  30,   1
** Section: Section-1  Profile: Profile-1
*Beam Section, elset=Set-1, material=Material-1, temperature=GRADIENTS, section=RECT
1., 1.
0.,0.,-1.
*End Part
**  
**
** ASSEMBLY
**
*Assembly, name=Assembly
**  
*Instance, name=beam-1, part=beam
*End Instance
**  
*End Assembly
** 
** MATERIALS
** 
*Material, name=Material-1
*Elastic
 <X0001>, 0.35
*Plastic
 3e+08,   0.
 6e+08, 0.18
 1e+09,  0.5
** ----------------------------------------------------------------
** 
** STEP: Step-1
** 
*Step, name=Step-1, nlgeom=NO
*Static, direct
0.02, 1., 
** 
** BOUNDARY CONDITIONS
** 
** Name: BC-1 Type: Displacement/Rotation
*Boundary
beam-1.Set-Left, 1, 1
beam-1.Set-Left, 2, 2
** Name: BC-2 Type: Displacement/Rotation
*Boundary
beam-1.Set-right, 2, 2
** 
** LOADS
** 
** Name: Load-1   Type: Concentrated force
*Cload
beam-1.Set-F, 2, <X0002>
** 
** OUTPUT REQUESTS
** 
*Restart, write, frequency=0
** 
** FIELD OUTPUT: F-Output-1
** 
*Output, field
*Node Output, nset=beam-1.Set-mesh
U, 
*Node Print, nset=beam-1.Set-mesh
U2,
** 
** HISTORY OUTPUT: H-Output-1
** 
*Output, history, variable=PRESELECT
*End Step
