*Heading
** Job name: Job-1 Model name: Model-1
** Generated by: Abaqus/CAE 2022
*Preprint, echo=NO, model=NO, history=NO, contact=NO
**
** PARTS
**
*Part, name=Part-1
*Node
      1,   -3.5999999,           0.
      2,           0.,           0.
      3,           0.,   -3.5999999
      4,  -1.79999995,  -1.79999995
      5,   -3.5999999,   -3.5999999
      6,  -7.19999981,   -3.5999999
      7,   -5.4000001,  -1.79999995
      8,  -7.19999981,           0.
      9,  -3.24000001,           0.
     10,  -2.88000011,           0.
     11,  -2.51999998,           0.
     12,  -2.16000009,           0.
     13,  -1.79999995,           0.
     14,  -1.44000006,           0.
     15,  -1.08000004,           0.
     16, -0.720000029,           0.
     17, -0.360000014,           0.
     18,           0., -0.360000014
     19,           0., -0.720000029
     20,           0.,  -1.08000004
     21,           0.,  -1.44000006
     22,           0.,  -1.79999995
     23,           0.,  -2.16000009
     24,           0.,  -2.51999998
     25,           0.,  -2.88000011
     26,           0.,  -3.24000001
     27,  -1.54285717,  -2.05714297
     28,  -1.28571427,  -2.31428576
     29,  -1.02857149,  -2.57142854
     30, -0.771428585,  -2.82857132
     31, -0.514285743,  -3.08571434
     32, -0.257142872,  -3.34285712
     33,  -3.34285712,  -3.34285712
     34,  -3.08571434,  -3.08571434
     35,  -2.82857132,  -2.82857132
     36,  -2.57142854,  -2.57142854
     37,  -2.31428576,  -2.31428576
     38,  -2.05714297,  -2.05714297
     39,  -3.96000004,   -3.5999999
     40,  -4.32000017,   -3.5999999
     41,  -4.67999983,   -3.5999999
     42,  -5.03999996,   -3.5999999
     43,   -5.4000001,   -3.5999999
     44,  -5.76000023,   -3.5999999
     45,  -6.11999989,   -3.5999999
     46,  -6.48000002,   -3.5999999
     47,  -6.84000015,   -3.5999999
     48,  -6.94285727,  -3.34285712
     49,  -6.68571424,  -3.08571434
     50,  -6.42857122,  -2.82857132
     51,  -6.17142868,  -2.57142854
     52,  -5.91428566,  -2.31428576
     53,  -5.65714264,  -2.05714297
     54,  -5.14285707,  -1.54285717
     55,  -4.88571405,  -1.28571427
     56,  -4.62857151,  -1.02857149
     57,  -4.37142849, -0.771428585
     58,  -4.11428595, -0.514285743
     59,  -3.85714293, -0.257142872
     60,  -6.84000015,           0.
     61,  -6.48000002,           0.
     62,  -6.11999989,           0.
     63,  -5.76000023,           0.
     64,   -5.4000001,           0.
     65,  -5.03999996,           0.
     66,  -4.67999983,           0.
     67,  -4.32000017,           0.
     68,  -3.96000004,           0.
     69,  -6.94285727, -0.257142872
     70,  -6.68571424, -0.514285743
     71,  -6.42857122, -0.771428585
     72,  -6.17142868,  -1.02857149
     73,  -5.91428566,  -1.28571427
     74,  -5.65714264,  -1.54285717
     75,  -5.14285707,  -2.05714297
     76,  -4.88571405,  -2.31428576
     77,  -4.62857151,  -2.57142854
     78,  -4.37142849,  -2.82857132
     79,  -4.11428595,  -3.08571434
     80,  -3.85714293,  -3.34285712
     81, -0.360000014,   -3.5999999
     82, -0.720000029,   -3.5999999
     83,  -1.08000004,   -3.5999999
     84,  -1.44000006,   -3.5999999
     85,  -1.79999995,   -3.5999999
     86,  -2.16000009,   -3.5999999
     87,  -2.51999998,   -3.5999999
     88,  -2.88000011,   -3.5999999
     89,  -3.24000001,   -3.5999999
     90,  -1.54285717,  -1.54285717
     91,  -1.28571427,  -1.28571427
     92,  -1.02857149,  -1.02857149
     93, -0.771428585, -0.771428585
     94, -0.514285743, -0.514285743
     95, -0.257142872, -0.257142872
     96,   -3.5999999, -0.360000014
     97,   -3.5999999, -0.720000029
     98,   -3.5999999,  -1.08000004
     99,   -3.5999999,  -1.44000006
    100,   -3.5999999,  -1.79999995
    101,   -3.5999999,  -2.16000009
    102,   -3.5999999,  -2.51999998
    103,   -3.5999999,  -2.88000011
    104,   -3.5999999,  -3.24000001
    105,  -3.34285712, -0.257142872
    106,  -3.08571434, -0.514285743
    107,  -2.82857132, -0.771428585
    108,  -2.57142854,  -1.02857149
    109,  -2.31428576,  -1.28571427
    110,  -2.05714297,  -1.54285717
*Element, type=B21
 1,  1,  9
 2,  9, 10
 3, 10, 11
 4, 11, 12
 5, 12, 13
 6, 13, 14
 7, 14, 15
 8, 15, 16
 9, 16, 17
10, 17,  2
11,  2, 18
12, 18, 19
13, 19, 20
14, 20, 21
15, 21, 22
16, 22, 23
17, 23, 24
18, 24, 25
19, 25, 26
20, 26,  3
21,  4, 27
22, 27, 28
23, 28, 29
24, 29, 30
25, 30, 31
26, 31, 32
27, 32,  3
28,  5, 33
29, 33, 34
30, 34, 35
31, 35, 36
32, 36, 37
33, 37, 38
34, 38,  4
35,  5, 39
36, 39, 40
37, 40, 41
38, 41, 42
39, 42, 43
40, 43, 44
41, 44, 45
42, 45, 46
43, 46, 47
44, 47,  6
45,  6, 48
46, 48, 49
47, 49, 50
48, 50, 51
49, 51, 52
50, 52, 53
51, 53,  7
52,  7, 54
53, 54, 55
54, 55, 56
55, 56, 57
56, 57, 58
57, 58, 59
58, 59,  1
59,  8, 60
60, 60, 61
61, 61, 62
62, 62, 63
63, 63, 64
64, 64, 65
65, 65, 66
66, 66, 67
67, 67, 68
68, 68,  1
69,  8, 69
70, 69, 70
71, 70, 71
72, 71, 72
73, 72, 73
74, 73, 74
75, 74,  7
76,  7, 75
77, 75, 76
78, 76, 77
79, 77, 78
80, 78, 79
81, 79, 80
82, 80,  5
83,  3, 81
84, 81, 82
85, 82, 83
86, 83, 84
87, 84, 85
88, 85, 86
89, 86, 87
90, 87, 88
91, 88, 89
92, 89,  5
 93,  4, 90
 94, 90, 91
 95, 91, 92
 96, 92, 93
 97, 93, 94
 98, 94, 95
 99, 95,  2
100,   1,  96
101,  96,  97
102,  97,  98
103,  98,  99
104,  99, 100
105, 100, 101
106, 101, 102
107, 102, 103
108, 103, 104
109, 104,   5
110,   1, 105
111, 105, 106
112, 106, 107
113, 107, 108
114, 108, 109
115, 109, 110
116, 110,   4
*Nset, nset=_PickedSet7, internal
  2,  3, 18, 19, 20, 21, 22, 23, 24, 25, 26
*Elset, elset=_PickedSet7, internal, generate
 11,  20,   1
*Nset, nset=_PickedSet8, internal
  1,  2,  9, 10, 11, 12, 13, 14, 15, 16, 17
*Elset, elset=_PickedSet8, internal, generate
  1,  10,   1
*Nset, nset=_PickedSet9, internal
  2,  4,  5, 33, 34, 35, 36, 37, 38, 90, 91, 92, 93, 94, 95
*Elset, elset=_PickedSet9, internal
 28, 29, 30, 31, 32, 33, 34, 93, 94, 95, 96, 97, 98, 99
*Nset, nset=_PickedSet10, internal
   1,   3,   4,  27,  28,  29,  30,  31,  32, 105, 106, 107, 108, 109, 110
*Elset, elset=_PickedSet10, internal
  21,  22,  23,  24,  25,  26,  27, 110, 111, 112, 113, 114, 115, 116
*Nset, nset=_PickedSet11, internal
  3,  5, 81, 82, 83, 84, 85, 86, 87, 88, 89
*Elset, elset=_PickedSet11, internal, generate
 83,  92,   1
*Nset, nset=_PickedSet12, internal
   1,   5,  96,  97,  98,  99, 100, 101, 102, 103, 104
*Elset, elset=_PickedSet12, internal, generate
 100,  109,    1
*Nset, nset=_PickedSet13, internal
  1,  8, 60, 61, 62, 63, 64, 65, 66, 67, 68
*Elset, elset=_PickedSet13, internal, generate
 59,  68,   1
*Nset, nset=_PickedSet14, internal
  5,  7,  8, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
*Elset, elset=_PickedSet14, internal, generate
 69,  82,   1
*Nset, nset=_PickedSet15, internal
  1,  6,  7, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59
*Elset, elset=_PickedSet15, internal, generate
 45,  58,   1
*Nset, nset=_PickedSet16, internal
  5,  6, 39, 40, 41, 42, 43, 44, 45, 46, 47
*Elset, elset=_PickedSet16, internal, generate
 35,  44,   1
*Nset, nset=Set-17, generate
   1,  110,    1
*Elset, elset=Set-17, generate
   1,  116,    1
*Nset, nset=Set-20, generate
   1,  110,    1
*Elset, elset=Set-20, generate
   1,  116,    1
*Nset, nset=Set-8
  5,  7,  8, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
*Elset, elset=Set-8, generate
 69,  82,   1
*Nset, nset=U1
 4,
*Nset, nset=U2
 3,
*Nset, nset=Set-mesh, generate
   1,  110,    1
*Elset, elset=_Surf-1_SPOS, internal, generate
 59,  68,   1
*Surface, type=ELEMENT, name=Surf-1
_Surf-1_SPOS, SPOS
*Elset, elset=_Surf-2_SPOS, internal, generate
  1,  10,   1
*Surface, type=ELEMENT, name=Surf-2
_Surf-2_SPOS, SPOS
** Section: Section-2  Profile: Profile-1
*Beam Section, elset=_PickedSet8, material=Elastic, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-1  Profile: Profile-1
*Beam Section, elset=_PickedSet7, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-4  Profile: Profile-1
*Beam Section, elset=_PickedSet10, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-3  Profile: Profile-1
*Beam Section, elset=_PickedSet9, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-10  Profile: Profile-1
*Beam Section, elset=_PickedSet16, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-9  Profile: Profile-1
*Beam Section, elset=_PickedSet15, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-7  Profile: Profile-1
*Beam Section, elset=_PickedSet13, material=Elastic, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-8  Profile: Profile-1
*Beam Section, elset=_PickedSet14, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-5  Profile: Profile-1
*Beam Section, elset=_PickedSet11, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
** Section: Section-6  Profile: Profile-1
*Beam Section, elset=_PickedSet12, material=MAT, temperature=GRADIENTS, section=CIRC
1.
0.,0.,-1.
*End Part
**  
**
** ASSEMBLY
**
*Assembly, name=Assembly
**  
*Instance, name=Part-1-1, part=Part-1
*End Instance
**  
*Nset, nset=_PickedSet7, internal, instance=Part-1-1
 6, 8
*Nset, nset=_PickedSet14, internal, instance=Part-1-1
 3,
*End Assembly
** 
** MATERIALS
** 
*Material, name=Elastic
*Elastic
 2.06e+10, 0.3
*Material, name=MAT
*Elastic
 3.06e+10, 0.3
*Plastic
   1e+07,   0.
 3.5e+07, 0.05
   4e+07, 0.15
 4.5e+07, 0.18
   5e+07, 0.23
 5.5e+07, 0.35
** 
** BOUNDARY CONDITIONS
** 
** Name: BC-1 Type: Displacement/Rotation
*Boundary
_PickedSet7, 1, 1
_PickedSet7, 2, 2
_PickedSet7, 6, 6
** ----------------------------------------------------------------
** 
** STEP: Step-1
** 
*Step, name=Step-1, nlgeom=NO, inc=2000
*Static, direct, stabilize, allsdtol=0.05, continue=YES
0.001, 1., 
** 
** LOADS
** 
** Name: Load-1   Type: Pressure
*Dsload
Part-1-1.Surf-1, P, <X0001>
** Name: Load-2   Type: Pressure
*Dsload
Part-1-1.Surf-2, P, <X0002>
** 
** OUTPUT REQUESTS
** 
*Restart, write, frequency=0
** 
** FIELD OUTPUT: F-Output-1
** 
*Output, field, variable=PRESELECT
*Node Print, nset=Part-1-1.Set-mesh
 U, COORD
** 
** HISTORY OUTPUT: H-Output-1
** 
*Output, history, variable=PRESELECT
*End Step
